### ISSUE TITLE
Overflow of search bar in smart phones

### ISSUE THREAD

**Issue by raashika03** [edamontology/edam-browser#102]
When we don't use search bar, scrolling is possible to the term details table

![Screenshot_2021-04-10-14-57-00-01](https://user-images.githubusercontent.com/45493793/114265440-66368200-9a0e-11eb-8393-a4f6ec1b1527.png)

When we use search bar, it's not possible to go down without scrolling in a single flow(taking care to not scroll inside the image) 

![Screenshot_2021-04-10-14-58-26-44](https://user-images.githubusercontent.com/45493793/114265465-8c5c2200-9a0e-11eb-9f6f-3102949b147a.png)

Few other websites search bar with no overflow condition

![Screenshot_2021-04-10-15-00-59-80](https://user-images.githubusercontent.com/45493793/114265542-f70d5d80-9a0e-11eb-94c3-63fbb961a9b8.png)

![Screenshot_2021-04-10-15-02-17-08](https://user-images.githubusercontent.com/45493793/114265549-fecd0200-9a0e-11eb-8417-3a7b80c0a00b.png)

So should I try changing Edam search bar similarly? To prevent this problem. @bryan-brancotte @matuskalas @hmenager

**Comment by secrashi** [comment]
Hey @raashika03, you addressed two issues here.

1. The search bar stretches and overflows out of the visible screen of the mobile.
2. We are not able to scroll down in a single flow when we click on a search bar.

For the first point, I noticed that when we click the search bar, it zooms out and it looks like overflow. Same as what you mentioned in #103, except there it was an input field box instead of a search bar. 
One possible solution to this problem could be stopping the page to zoom out, whenever we click an input field box. Are you planning to do the same or do you have another idea to stop this overflow?

For the second point, I saw that you already made a PR for reducing the tree box size. Can we also add a scrollbar on the right side to further improve the user accessibility and user experience for the website?

**Comment by raashika03** [comment]
For 2nd point this's [where](https://github.com/edamontology/edam-browser/issues/72#issuecomment-816303405)    I'm working. May be @bryan-brancotte Will suggest something better than adding scrollbar. 
For 1st point, I'll not stop the zooming of the content because that'll remove the focus from the selected element, so will just adjust them to fit the view screen. 
Hope this answer your points @secrashi 😀

**Comment by bryan-brancotte** [comment]
Hi @raashika03 

I agree with @secrashi that this issue is very similare to #103 where smartphone browser zoom in when clicking on a search bar that is too small to be read otherwise. Never the less let the two remain open as solution could not be the same for both use case.

**Comment by bryan-brancotte** [comment]
Following original idea done in #169, adding viewport to index.html and updating width with 8da0b2a22d4bd9bc8e81004e198d36c4776c18e4, issue is solved
