### ISSUE TITLE
Making tree box extendable vertically!

### ISSUE THREAD

**Issue by secrashi** [edamontology/edam-browser#157]
Hello @bryan-brancotte @matuskalas @hmenager, this issue is about making the tree box extendable vertically using a cursor. As discussed in comments of #91, I implemented this feature roughly and the video of same is attached below:

https://user-images.githubusercontent.com/56053777/116521650-ddff1a80-a8f1-11eb-8211-80fcdd463c98.mp4

I thought of extending the box by stretching the bottom limit of the box, but then a new user won't know about this functionality, so I planned to add a button. Can you review and let me know if this would be a good add-on for our website? Also, since I already worked on this partially( not yet implemented to tree box), so it won't take much time and I'll soon make a PR!

**Comment by raashika03** [comment]
![image](https://user-images.githubusercontent.com/45493793/116526174-f0c81e00-a8f6-11eb-821a-b290a671c3c4.png)
Resizing(only vertically) using cursor will be a better option here. Providing buttons for everything will unnecessarily add up in the contents.

**Comment by raashika03** [comment]
Two things can be done here for better UI:
1) provide resizing using cursor for devices with mouse.
2) provide a button to appear for devices with touchpad.
This approach will enhance UI & UX and is likely to solve scrollability issue for smaller screens.

**Comment by secrashi** [comment]
You are right @raashika03, but then a user might not get the idea of the existence of this feature. Let's see what our mentors suggest in this!

**Comment by raashika03** [comment]
> 
> but then a user might not get the idea of the existence of this feature. 

I agree with you @secrashi but then if we see like that then even feature like dragging of tree map is not shown anywhere explicitly.
But still it's known to users and it's still helpful to have it without any button.

> 
>  In the case of using a cursor, I might never notice this functionality ( until it's a mobile screen where we have an issue of scrollability)

A user will notice it with the change in cursor from pointer to resize one when they will scroll down to the empty spaces.
Tree map is like an image and in most of the websites one can resize images or view screen, so users must be acquainted. 

Yes, let's wait for the mentors to suggest. what would be the best.

**Comment by bryan-brancotte** [comment]
Hi both of you,

This issue is very interesting, and I would like to go even deeper and think of why we would add a vertical expand button. It is because we want to use all the space we have while keeping the right detail panel, and #141 worked in this direction. I would like to go further and introduce the second part : have in fullscreen the detail panel. There is an old feature that I disabled a long time ago as it was redundant with the detail panel on the right : the floating detail panel [code](https://github.com/edamontology/edam-browser/blob/c8b41cc78f5247d48ba7b6f40afdba8948d7df76/js/tree-reusable-d3.js#L39): 

![tooltip](https://user-images.githubusercontent.com/11556772/116576341-c2a30800-a90f-11eb-85a6-48dfb4193b85.gif)

I think that If we could put more detail in this panel, we would solve the need adressed here, with a very intuitive approach.

What are you views ?

**Comment by raashika03** [comment]
so do you mean, 
1) Have details term table appear on hovering over a node when tree map is in full screen mode?
Did I understood right @bryan-brancotte ?
So, vertical extension of tree map isn't needed, if we'll go with option 1. This seems useful to me.

empty space can be covered in other more useful ways. May be that bookmark option on which @secrashi is working.

**Comment by bryan-brancotte** [comment]
I would say yes @raashika03 
Here is a draft of what I have in mind (pure photoshopping)
![draft](https://user-images.githubusercontent.com/11556772/116607521-60a7ca00-a932-11eb-82a3-3ba6dda53804.png)

Adding "Community usage" would be done later, and only on demande as it consume network and we could end up block with too much request on each service.

**Comment by raashika03** [comment]
Ok @bryan-brancotte I understood well. So may be you can create an issue for this :) then one can work. :sweat_smile:
