### ISSUE TITLE
make tooltips responsive

### ISSUE THREAD

**Issue by HagerDakroury** [edamontology/edam-browser#202]
While reproducing #189, I noticed that the tooltip is not responsive (gets cropped when resizing the browser)

![tooltipNotResponsive](https://user-images.githubusercontent.com/37930475/119331322-8309da80-bc87-11eb-8db2-9e1f38274dce.gif)

It should be accommodating this by wrapping or moving to the center/left.

**Comment by bryan-brancotte** [comment]
Good point, I have no clue on how to do it !

**Comment by HagerDakroury** [comment]
hi, @bryan-brancotte I'm trying to start tackling this but I'm clueless as well. Do you think we can try to figure it out together? 
I think the first direction may be to look into styling this in a more responsive way (however the main details panel is responsive normally so maybe that's not the issue here)

Any thoughts on where to start?

**Comment by bryan-brancotte** [comment]
Hi @HagerDakroury , I hopped you had a clue when you created the issue because I did not have one. Just an idea, but maybe we can at [this moment](https://github.com/edamontology/edam-browser/blob/main/js/tree-reusable-d3.js#L202-L204) get to know the width of the tooltip container, the width of the container and adapte it to not overflow (`tooltip.width=min(400,parent.width-tooltip.x)`). We would also  switch to rendering it on the left of the pointer when we see that x+width>width of the parent. This idea are very speculative, I hope It will help.

**Comment by HagerDakroury** [comment]
@bryan-brancotte are the offsets here based on trial and error? [code](https://github.com/edamontology/edam-browser/blob/668dabd070333897fc87ca5c7306d66d6f7629e2/js/tree-reusable-d3.js#L202-L204) 

I'm at the stage of toggling the tooltip to the left but not sure what offset to follow. Or if there is a way to easily mirror the positions?

**Comment by bryan-brancotte** [comment]
Yes, the offsets were manually set to place it close to the pointer but not on it.

On the left is a good option, maybe in d3.js there is a way to have tooltip, but I am not aware of so at the time I built the tooltip as it is, with manual location and placement. So here I would go for a ```tooltip.style("left", (d3.event.layerX-20-width_of_the_tooltip) + "px")```

**Comment by HagerDakroury** [comment]
> Yes, the offsets were manually set to place it close to the pointer but not on it.
> 
> On the left is a good option, maybe in d3.js there is a way to have tooltip, but I am not aware of so at the time I built the tooltip as it is, with manual location and placement. So here I would go for a `tooltip.style("left", (d3.event.layerX-20-width_of_the_tooltip) + "px")`

Thanks a lot! 💯 I was stuck for a while doing the math 😄
