### ISSUE TITLE
Design loading different version of EDAM

### ISSUE THREAD

**Issue by HagerDakroury** [edamontology/edam-browser#216]
## Feature

Loading different versions of the same ontology (just EDAM for now).
How would that look like UI/UX wise? Will comparing versions be added? , etc.

Feel free to share your design ideas/suggestions!

Edit (Bryan): Let us try to not look at already proposed solution. To propose a design, we can use `<details>...<summary>...` to hide it by default. check here for more details https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287

**Comment by bryan-brancotte** [comment]
Hi,

<details>
  <summary>Here is my proposition (click to expand)</summary>

For now we have two button, Edam, and Custom. The second is almost not used. My proposition is to have two menu-buttons, the first to have the branch (or the ontology) and the second to have the version (when relevante i.e not with a custom ontology)
![Capture d’écran de 2021-06-16 09-48-21](https://user-images.githubusercontent.com/11556772/122216439-b3225300-ceac-11eb-8342-31c0a2db080e.png)
![Capture d’écran de 2021-06-16 09-48-35](https://user-images.githubusercontent.com/11556772/122216441-b3225300-ceac-11eb-8cd9-981d3d4350fc.png)

</details>

P.S: to have a by default collapsed area, check https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287

**Comment by hmenager** [comment]
Here's mine
<details>
<summary>click for details</summary>
![image](https://user-images.githubusercontent.com/1140736/122347293-2928c780-cf4a-11eb-9c07-1d8224a1fe80.png)

</details>

**Comment by HagerDakroury** [comment]
So, this is an initial idea based on our discussion. Branch and versions are separated + the custom option is moved outside. Will be adding any modifications here.

![designidea](https://user-images.githubusercontent.com/37930475/122359227-ab6ab900-cf55-11eb-921f-d39c314ab6bc.gif)


Should we include any design ideas for the custom popup window in this issue as well?

**Comment by matuskalas** [comment]
Hey all, sorry for not being able to take part in the morning chats this week.

I agree with the split. A couple of notes:
- Should the Version menu show the loaded version when closed, or do you prefer if that's only elsewhere?
- Branch should be renamed, unless it can load branches from GitHub repos 😉
- Perhaps Filter would be a better name. Inside the menu
    - "sub-ontology" instead of "branch"
    - "concepts" instead of "terms"
- Custom could be hidden before it starts working. And probably renamed to Ontology or so, enabling switching between the ready, "compiled" ontologies. Unless it will work so that you can insert a URL link to .owl file.

An alternative to consider:
- One dropdown called Filter
- One dropdown called Load (this would have versions for now, additional ontologies later. EDAM-bioimaging to start with)

**Comment by bryan-brancotte** [comment]
Hi all,

I think we should load the ontology right after clicking on a sub-ontology or a version.

Indeed branch can be confusing, fixed with 48f5f6f030ac77f31a7367eb240f33b60c205de7 (for branch loading, read hereafter :wink: ), and terms-> concepts with 6c38a0d5787e14df80f59bbc7b5c37c1fe8f30fc 

If I understand you correctly @HagerDakroury , the custom option you talk is a feature we talked this morning, the idea is to be able to load a custom version of the ontology, maybe even a commit hash, a branch, or a fork ! It would be a super cool feature but it is not available yet as we would need to be able to either read an owl file, or convert it on the fly, two things we cannot do yet. (in the example here after I still kept it as it would be a cool feature)

The "Custom" button is working (always have been !). But as far as I know loading custom ontology is not used, so we can :
 * make it less visible
 * rework the popup if needed in an other issue.
Note that code of this "Custom ontology loading" will share code with the load commit hash or fork.

For the two drop down, instead of rendering names ("sub-ontology", "branch", ...), we should render what is selected :

![Peek 17-06-2021 11-28](https://user-images.githubusercontent.com/11556772/122370129-1cfb3500-cf5f-11eb-8187-449ad0c8c4bd.gif)

I tried to add title inside the dropdown (`<li class="disabled"><a href="#">Versions:</a></li>`), but it does not look good.

**Comment by HagerDakroury** [comment]
> * Should the Version menu show the loaded version when closed, or do you prefer if that's only elsewhere?

I believe both menus (filter and version) should show the chosen option (like in @bryan-brancotte's design of the version). Since the version is shown elsewhere in the tree-controls. Do you think it will be redundant to also show it in the menu?

> * Branch should be renamed, unless it can load branches from GitHub repos 😉
> * Perhaps Filter would be a better name. Inside the menu

Good point!

> * Custom could be hidden before it starts working. And probably renamed to Ontology or so, enabling switching between the ready, "compiled" ontologies. Unless it will work so that you can insert a URL link to .owl file.
> 

We did actually discuss this idea (insert a URL link to .owl file) and agreed it should be included in the custom option.

I'm sure if it should be included in this issue (and hence, we keep the custom option). Technically, it's in the same scope(loading different versions of EDAM) but I'm not sure if it'll be in the same scope code-wise. Any thoughts? @bryan-brancotte

**Comment by HagerDakroury** [comment]
> If I understand you correctly @HagerDakroury , the custom option you talk is a feature we talked this morning, the idea is to be able to load a custom version of the ontology, maybe even a commit hash, a branch, or a fork ! It would be a super cool feature but it is not available yet as we would need to be able to either read an owl file, or convert it on the fly, two things we cannot do yet. (in the example here after I still kept it as it would be a cool feature)
> 

Yes exactly, it's a rework of @hmenager's custom version option (not related to the current custom functionality) and it's for the purpose of loading a custom version of EDAM from a URL.

Not sure if it should be included in the initial design or not though.

**Comment by bryan-brancotte** [comment]
> I believe both menus (filter and version) should show the chosen option (like in @bryan-brancotte's design of the version). Since the version is shown elsewhere in the tree-controls. Do you think it will be redundant to also show it in the menu?

Yes it is definitly redundant, if we can find a way to avoid this redundancy we should I think.

> I'm not sure if it should be included in this issue (and hence, we keep the custom option). Technically, it's in the same scope(loading different versions of EDAM) but I'm not sure if it'll be in the same scope code-wise. Any thoughts? @bryan-brancotte

I think we should, for the design, keep this custom version included, and when implementing it we should comment it as long as we are not able to do it (not the same scope code-wise as you say). This way we will have a good UI, also ready for the day we load the owl (semi)directly

**Comment by HagerDakroury** [comment]
> Yes it is definitly redundant, if we can find a way to avoid this redundancy we should I think.

The meta info in the tree is valuable though (have date and links to the file). So, I'm honestly not sure which of the two version-info is less needed.


> I think we should, for the design, keep this custom version included, and when implementing it we should comment it as long as we are not able to do it (not the same scope code-wise as you say). This way we will have a good UI, also ready for the day we load the owl (semi)directly

I'd actually love to start working on this feature along with the current issue. So, I vote we should at least agree on a design for it.

**Comment by hmenager** [comment]
Thanks a lot for this constructive discussion @HagerDakroury  @bryan-brancotte @matuskalas ! I really like a lot the latest variation suggested by @bryan-brancotte in https://github.com/edamontology/edam-browser/issues/216#issuecomment-863086847.

My only *very very minor* comment is that maybe it would be nice to have the version selector to the left and the filter selector to the right, instead of the other way around (but this is because I have been conditionned to see hierarchies in UIs represented from left to right, and filter feels like a more fine-grained option than version). Feel free to disregard completely!

**Comment by bryan-brancotte** [comment]
Thanks Hervé,

I did not have a reason for putting the filter selection on the left other than "it was there before". So yes let's go for it as you have a reason to put it on the right.

**Comment by HagerDakroury** [comment]
> My only _very very minor_ comment is that maybe it would be nice to have the version selector to the left and the filter selector to the right, instead of the other way around (but this is because I have been conditionned to see hierarchies in UIs represented from left to right, and filter feels like a more fine-grained option than version). Feel free to disregard completely!

totally agree!

**Comment by HagerDakroury** [comment]
So, would that mean including the custom options in the dropdown menu like https://github.com/edamontology/edam-browser/issues/216#issuecomment-863086847? those options are custom ontology, commit hash or fork

**Comment by hmenager** [comment]
> So, would that mean including the custom options in the dropdown menu like [#216 (comment)](https://github.com/edamontology/edam-browser/issues/216#issuecomment-863086847)? those options are custom ontology, commit hash or fork

Yes, exactly!

**Comment by bryan-brancotte** [comment]
From 21/07/05 meeting,

Design from https://github.com/edamontology/edam-browser/issues/216#issuecomment-863086847 is ok

add tooltip to buttons, "subset" or "sub-section" for the left one, "version" for the right one.
