### ISSUE TITLE
Making URL link copy-able and correct

### ISSUE THREAD

**Issue by alaninmcr** [edamontology/edam-browser#43]
The text of the URL shown for format_3620 is correct. However, the text cannot be copied and when clicked the URL is https://ifb-elixirfr.github.io/edam-browser/#http://edamontology.org/ - which is incorrect as the URL.

It is not clear how the correct URLs can be copied.

**Comment by bryan-brancotte** [comment]
Hi, indeed copy pasting the "good" url is tricky :/ Issue #40 already cover the need of an easy way to copy the "good" url.

The text in the left part, the tree is not meant to be copy/paste-able, on the right part the `Term` can be copied easily so I am not sure we talk about the same thing.

**Comment by alaninmcr** [comment]
I think my issue is the same as #40 Although the text "xslx" can be copied the correct URI cannot be copied. 

Wouldn't a solution be to make the URI point to the correct URI rather than the browser one?

**Comment by bryan-brancotte** [comment]
The idea is to quickly have a link to share for browsing inside the browser, also pointing to http://edamontology.org/format_3620 ends to another browser, the allow user to work in this browser (while proposing links to others browsers)

**Comment by alaninmcr** [comment]
Could you not add a second line that links to http://edamontology.org/format_3620 ? I think it is confusing that the URI as shown does not actually link to the URI :-)

**Comment by bryan-brancotte** [comment]
I do not want to add redundant information as the link http://edamontology.org/format_3620 is already present in "Links" section (while being for now broken cf #44 ) in the lower part "Community usage". The upper part is made for "inside" information so having an outgoing link is not the right place. 

At the time it was built, I though every one knew the trick to copy text content of an href link, so the question was to disable the link, or make it useful and point inside the app. I chose the second option. It turned out that very few knows the tricks to copy text of links so #40 arise and either we will disable the links completely, or add a button to copy the URI and keep the URL inside the app.

I add it to #40 that having a link that point not where it suggest can be confusing.

**Comment by HagerDakroury** [comment]
should be closed with #40 ? @bryan-brancotte

**Comment by bryan-brancotte** [comment]
Definitely @HagerDakroury  !
