### ISSUE TITLE
Display term relationships which are relevant in term creation form

### ISSUE THREAD

**Issue by hmenager** [edamontology/edam-browser#50]
### Edit:

`Is Identifier Of` does not exist yet, and should be created, the others have been done in #174

### Original post

The relationships showed in the form should be only the ones for the type of concept considered.
Here's a table of which relationship should be showed, depending on the type of concept the user suggests.
(Please not `Is Identifier Of` does not exist yet, and should be created).

|relationship|applicable to| status |
|---------------|-----------------| ----- |
|Parent|all| nothing to do |
|Has Topic|Operation, Data| done |
|Is Format Of|Format| done |
|Has Input|Operation| done |
|Has Output|Operation| done |
|Is Identifier Of|Identifier| to do |

**Comment by bryan-brancotte** [comment]
Hi @Annysah , hi all

The edam-browser allows to browse, but also propose changes in the ontology, when proposing a change in a concept, or a new concept, multiple field are proposed in the edition form and some are not pertinent. This form can be accessed by clicking on the “edit” icons at the top-right corner of this right panel.

To understand a little more on how work the browser and the edition ability, I recommend to take a look at the [publication](https://doi.org/10.21105/joss.00698)

**Comment by pooja2299** [comment]
Hi @hmenager . I would like to work on this issue.

**Comment by pooja2299** [comment]
I would like to ask few questions:
1. Relationship to be showed for 'Topic' is not mentioned in the table above.
2. What needs to be done for other types of concepts that are not mentioned in the table ? Does it remain same as before.

**Comment by matuskalas** [comment]
Thanks @Annysah and @pooja2299 for taking this task, it's a very important improvement which will be very useful for both users and EDAM maintainers! 👍🏽

**Comment by matuskalas** [comment]
>     1. Relationship to be showed for 'Topic' is not mentioned in the table above.

Indeed, _**Topic**_ has no relations. 😉

>     2. What needs to be done for other types of concepts that are not mentioned in the table ? Does it remain same as before.

The other types are mentioned in the table (_**Operation**_, _**Data**_, _**Identifier**_, _**Format**_).

Does this answer your question @pooja2299?

**Comment by pooja2299** [comment]
> > ```
> > 1. Relationship to be showed for 'Topic' is not mentioned in the table above.
> > ```
> 
> Indeed, _**Topic**_ has no relations. 
> 
> > ```
> > 2. What needs to be done for other types of concepts that are not mentioned in the table ? Does it remain same as before.
> > ```
> 
> The other types are mentioned in the table (_**Operation**_, _**Data**_, _**Identifier**_, _**Format**_).
> 
> Does this answer your question @pooja2299?

Yes @matuskalas . Thanks :+1:

**Comment by Annysah** [comment]
> This form can be accessed by clicking on the “edit” icons at the top-right corner of this right panel.

Hello @bryan-brancotte hello all, 
Please can you point me to how to access the edit icons

**Comment by raashika03** [comment]
> 
> Please can you point me to how to access the edit icons

![IMG_20210412_054430](https://user-images.githubusercontent.com/45493793/114326502-bd456f80-9b52-11eb-911e-ec1400ef19e4.jpg)
These two are the edit icons.

**Comment by HagerDakroury** [comment]
Hi, was looking at this since is identifier to is already implemented in #177 and have 2 Qs:

1. The expected behavior is the irrelevant terms not being displayed at all in the form, right? because now whenever I try to edit a term, all options are still displayed.
2. Is the edit form still functional? looks like all edits are disabled right now.

**Comment by bryan-brancotte** [comment]
> Hi, was looking at this since is identifier to is already implemented in #177 and have 2 Qs:
> 
> 1. The expected behavior is the irrelevant terms not being displayed at all in the form, right? because now whenever I try to edit a term, all options are still displayed.

Indeed irrelevant should not be displayed. I did not test enough the code not my code before merging https://github.com/edamontology/edam-browser/pull/177, and merge not working code, sorry for that.

> 2. Is the edit form still functional? looks like all edits are disabled right now.

It is now as I have pushed ~one~ ~two~ **multiple** patches....

### ... BUT ...

When creating the github template issue, many attributs are forgotten... Indeed [here](https://github.com/edamontology/edam-browser/blob/main/js/edit.js#L136) we list all text fields, and then we find all search-term for parents [there](https://github.com/edamontology/edam-browser/blob/main/js/edit.js#L138-L140) The bug is that now we have search for not only parents, but also is_identifier_of, has_topics, ...

So the term are now displayed, but `sendToGitHub` should be corrected to transmit all informations

**Comment by bryan-brancotte** [comment]
P.S: feel free to fix it @HagerDakroury, I also can, up to you !

**Comment by HagerDakroury** [comment]
> It is now as I have pushed ~one~ ~two~ **multiple** patches....
> 

Awesome, it looks like most fields are functional again indeed.
A Q though, this should be clickable, right? 
![notclickable](https://user-images.githubusercontent.com/37930475/122565028-4e026500-d046-11eb-9bc9-2cc9987bd762.gif)


> ### ... BUT ...
> When creating the github template issue, many attributs are forgotten... Indeed [here](https://github.com/edamontology/edam-browser/blob/main/js/edit.js#L136) we list all text fields, and then we find all search-term for parents [there](https://github.com/edamontology/edam-browser/blob/main/js/edit.js#L138-L140) The bug is that now we have search for not only parents, but also is_identifier_of, has_topics, ...
> 
> So the term are now displayed, but `sendToGitHub` should be corrected to transmit all informations

I also noticed that some not edited terms are still reported in the Github issue as a modification. Is this the expected behavior here? 
For example, clicked an item and didn’t edit anything but parents still reported as new. Upon inspecting the links, look like the second parent is reported as an edit to the first.

![reporting](https://user-images.githubusercontent.com/37930475/122565725-1811b080-d047-11eb-88ce-5189f702fbb0.gif)

**Comment by HagerDakroury** [comment]
> P.S: feel free to fix it @HagerDakroury, I also can, up to you !

Sure! I'd like to work on this. Just need to pinpoint the exact bug(s)!
