### ISSUE TITLE
Provide a more explicit placeholder text for the search box

### ISSUE THREAD

**Issue by hmenager** [edamontology/edam-browser#52]
It is not currently obvious that the search box located top right allows to search for concepts within EDAM:

![image](https://user-images.githubusercontent.com/1140736/112717195-53d72700-8eeb-11eb-87c3-ebadbc948527.png)

Replacing this text with something more explicit like "Search for concepts, type at least two letters here.". An additional magnifying glass icon (using bootstrap classes) might also improve the explicitness of the interface.

**Comment by pooja2299** [comment]
Hi, I am Pooja, an outreachy applicant. I would like to work on this issue. @hmenager Can you plse assign this to me?

**Comment by matuskalas** [comment]
Thank you @raashika03 for your pull request! @pooja2299 please feel free to suggest your solution!
We're very happy that you're interested in this project! 😸

**Comment by matuskalas** [comment]
A question for more native English speakers: Is it better here to write **letters** or **characters**?
(or just say **... please start typing**?)

**Comment by raashika03** [comment]
character sounds more technical, so letters seems better cause everyone using the edam browser ain't from technical background.

**Comment by Marlene7963** [comment]
Use of letters is a better choice. A user will find it easy to understand how to use the search box when they see "Type at least two letters" as opposed to "type at least two characters" 
A user will often find "please start typing" to be politely confusing because they won't know what they are supposed to type as the placeholder does not clearly say the use of that search box. 
The placeholder text content should be a clear explanation of the action to be taken

**Comment by matuskalas** [comment]
Thanks a lot for the answers @Marlene7963 and @raashika03! 🥇

**Comment by bryan-brancotte** [comment]
Hi, thanks both to you both !

@raashika03 I am merging your solution first as you submitted first

@Marlene7963 once #54 merged, could you resolve conflict so I can also merge you solution as it is an improvement (icon not overflowing

**Comment by bryan-brancotte** [comment]
Fixed with #54 and  #55

**Comment by pooja2299** [comment]
@matuskalas Thank you for assigning me this issue. I was busy with my college classes in the morning. 
My suggestion would be to write -"Search your concepts here (Enter atleast two letters)". Or what @raashika03 suggested is also fine. 
As @bryan-brancotte has merged the above two solutions can I also submit my solution since it was assigned to me ?

**Comment by bryan-brancotte** [comment]
Sorry @pooja2299 I missed that it was assigned, indeed please submit your solution

**Comment by matuskalas** [comment]
Hi @pooja2299, no worry! Indeed please do, or if you want you can submit an improvement to what has been merged. Please also feel free to grab another issue (you can either solve it immediately or ask for getting it assigned) 😉

**Comment by pooja2299** [comment]
Hi @matuskalas. Thanks a lot! I have added my solution file. Please have a look. 
PS: I had some issue in my laptop, so had to reinstall linux. so couldn't reply yesterday.
I will start working on other issues as well .
