### ISSUE TITLE
Aligning the box to make the content fully visible.

### ISSUE THREAD

**Issue by secrashi** [edamontology/edam-browser#81]
**Problem:** On hovering over the number and looking for associated elements, the content is not fully visible. 
**Proposed Solution:** On hovering, the box opens either on the left side or right side, where there's enough space for the content.
_P.S. This problem occurs when we resize the tab in desktop view!_

![IMG_20210405_084316](https://user-images.githubusercontent.com/56053777/113534008-0fcfda80-95ed-11eb-929d-ed9c4d091dc8.jpg)

I'll make the content in the box fully visible by aligning the position of the box.

**Comment by raashika03** [comment]
Same suggestion as #83 (because this's something needed and mentors won't disapprove this) just to add up my views: this tooltip content appears like this by default ig so you'll have to look for a way to change for all the elements which does have tooltip in the details term box but this varies with each type (edam, data, format, operation, topic...) so may be, you'll have to do a little more work than simple changes in css code, you may have to dive deep into the js code also. Cause fields which are generated are controlled using js.
Example for what I'm talking about:
For data, fields which appear:
![Screenshot from 2021-04-05 10-57-14](https://user-images.githubusercontent.com/45493793/113540922-c12b3c00-95fe-11eb-949b-2bd5a0e93d29.png)
For topic:
![Screenshot from 2021-04-05 10-57-30](https://user-images.githubusercontent.com/45493793/113541015-fafc4280-95fe-11eb-898a-3ec32e5a4107.png)
You can clearly see the difference in the content of bio.tools, Biosphere...

**Comment by secrashi** [comment]
Yes, I'm aware of this. Still, thanks for taking out the time to let me know this! Also, I'll remember to add PR's directly for these types of issues.

**Comment by matuskalas** [comment]
Awesome @secrashi if you want to work on this!!! And well spotted! 👍🏽

**Comment by secrashi** [comment]
Thank you!

**Comment by bryan-brancotte** [comment]
Hi @secrashi 

Thanks for pointing it out :+1: 

Here are some direction : 
 * understand how this box appears, what is its name. Hint : we use bootstrap 3
 * understand how it could be place elsewhere
 * find in the js code where this box is build, and update the code.

This issue is not an easy one, I would say medium, but still It is open for solving.

**Comment by kellydoleo** [comment]
Hi @secrashi did you make a pull request for this yet? Is there any way I can provide help on this issue? @bryan-brancotte

**Comment by secrashi** [comment]
Hi, @kellydoleo No I haven't made a PR for this yet, I was inactive for some time due to my exams, but I'll make the PR soon. I'll ask you if I need any help, thanks.

**Comment by bryan-brancotte** [comment]
Hi @secrashi 

It is a good proposition that you made in #113, although we might face the same problem when using mobile (even if mobile is not our main target). Maybe you should dig a little more on the data-placement, and see if there is any option that would allow to place the box on the right when possible, otherwise on the left.

**Comment by secrashi** [comment]
Hi @bryan-brancotte, I thought of that, but on a mobile phone, we can't hover over it, and when we click it, it opens in a new tab. So, I thought It'll not matter. If you want I can create an option that would allow placing the box on the right when possible, otherwise on the left, though I'm not exactly sure if it would be useful. Please let me know if I'm wrong!

**Comment by bryan-brancotte** [comment]
Hi, you are right about smartphone, although a long press expand the popover and propose to save the link, not very user-friendly but it works.

*Personal opinion: I prefer to have, when possible, the popover on the right, it covers less texts.*

So, the goal here is to find a way to display it on the right, otherwise on the left, I recommend you to do some search on popover with bootstrap, even if we are using bootstrap 3, documentation of bootstrap 4 will help you.

**Comment by raashika03** [comment]
Can be closed via #113 @bryan-brancotte

**Comment by raashika03** [comment]
@bryan-brancotte can be closed via #113

**Comment by secrashi** [comment]
Thanks for reminding @raashika03, Closing with #113!
